### ISSUE TITLE
publish 2.1.0

### ISSUE THREAD

**Issue by betehess** [alexander-myltsev/parboiled2#11]
Hi,

Could you please publish 2.1.0? I do not see it on http://dl.bintray.com/content/alexander-myltsev/maven/org/parboiled/parboiled_sjs0.6_2.11/

Thank you so much for the port :-)

**Comment by alexander-myltsev** [comment]
There is a branch for this already: https://github.com/alexander-myltsev/parboiled2/commits/scala-2.11-scalajs-0.6.x. I ported core and examples. The problem is with scala-parser example (see it in the end of https://github.com/sirthias/parboiled2/issues/131).

@lihaoyi, is there any progress in that direction?

If no then I can publish without that example.

**Comment by lihaoyi** [comment]
Haven't put time into it. Perhaps you could go ahead first without it?

**Comment by smungee** [comment]
Would be great if you could publish 2.1.0. 

Also, what are your thoughts on using this in production? Our use-case is we'd like to write a PEG-grammar that can validate user-input and generate AST, and we'd like this code to be reusable in the frontend and backend. That's why we're considering writing this in Parboiled2+Scala.JS.

**Comment by alexander-myltsev** [comment]
David Barri published parboiled2 under `"com.github.japgolly.fork.parboiled" %%% "parboiled" %% "2.1.0"`.

As for using in production. parboiled2 depends only on shapeless and scala-macros. pb2 source required a few changes to make it work on scala-js: https://github.com/alexander-myltsev/parboiled2/commit/9509b4bdce71455750da87425918f03feeba8e05. As long scala-js compiler works fine, pb2 should too. Still, pb2-scalajs does not contain any javascript tests to ensure it works. You are welcome to try it in your project, and share your experience with us.

**Comment by smungee** [comment]
Thanks @alexander-myltsev, will report back any issues we find.
